api/desecapi/models.py, api/desecapi/templates/emails/captcha/content.txt, api/desecapi/templates/emails/domain-dyndns/content.txt, api/desecapi/templates/emails/donation/donor-content.txt, api/desecapi/tests/testdomains.py, devadmin/Dockerfile
The docker image richarvey/nginx-php-fpm that we're using has switched
its default to PHP 7, breaking the way our poweradmin is set up.
This PR enforces the use of the PHP 5 docker image.
=> fix(devadmin): enforce PHP 5

api/desecapi/authentication.py, api/desecapi/tests/testdyndns12update.py, api/desecapi/views.py
Problem:
- For dynDNS domain updates: When the basic auth username (signifying
the domain name) was invalid or missing, we returned 404 so far.
However, as the user is likely to perceive the domain name as a
username and the token as the password, 401 is more reasonable.
Solution:
- We now return 401 if the username is invalid.
- If it is missing, we determine the domain name based on the token
and proceed as usual. If this is ambiguous, we return 409.
=> fix(api): fix HTTP error codes for basic auth, closes #26

nslord/cronhook/secure-zones.sh
- So far, we had a wildcard delegation for *.dedyn.io, but that is
not the right approach when DNSSEC is used (RFC 4592, Sec. 4.2.1).
- These delegation records need to be deleted upon zone deletion.
The deletion code is already set up to handle this.
=> fix(nslord): add NS records for dedyn.io delegations, fixes #11

dblord/initdb.d/11-pdns-lord-REFERENCES.sql, dbmaster/initdb.d/11-pdns-master-REFERENCES.sql
Previously, we only had foreign key contraints for the `records` and the `domainmetadata` table.
Now we're also adding them for the `comments` and `cryptokeys` table. The SQL statements are taken from https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/enable-foreign-keys.mysql.sql
=> fix(db): improve foreign keys for dblord/dbmaster

api/desecapi/models.py, api/desecapi/pdns.py, api/desecapi/serializers.py, api/desecapi/settings.py, api/desecapi/tests/testdomains.py, api/desecapi/views.py
- better error codes
- make domain DELETE idempotent
- wrap Domain database writes in transaction, commit only when pdns operations are successful
TODO:
- fix testCantDeleteOtherDomains test
- done
- return a reasonable error if pdns operations fail (currently 500)
- done (if domain already exists, return 409)
- If a user is acting (GET, DELETE, ...) on a domain that belongs to another user, we return 404 (because the Django queryset is empty). 403 may be more appropriate, but it leaks a bit of information
- not doing this now, problem is rather esoteric
=> api: Improve error handling

api/Dockerfile, api/cronhook/crontab, api/cronhook/start-cron.sh, api/entrypoint.sh
Added cronhook that executs the privacy chores.
Chosen 2:55am UTC without any particular reason.
Environment get dumped into container at /etc/environment. Potential security thread? It contains sensitive data.
Closes nils-wisiol/desec-internal#9.
=> cronhook, privacy chores

api/desecapi/pdns.py, api/desecapi/tests/testdomains.py, api/desecapi/tests/testdyndns12update.py, api/desecapi/tests/testdynupdateauthentication.py
This decreases DNS update time at the nsmaster to approx. one 1 second.
Adopted unit tests, as most tests now need to access the last-but-one request to make their assertions.
Added a unit test to see if our code PUTs on the /notify endpoint of the pdns API.
Calling notify_zone immediately after creating a zone results in a 500 error at the pdns API. For discussion, see also #40.
Also, added a minor PEP style fix.
=> On Update, Command Lord to Notify Master Immediately

dbapi/initdb.d/99-finish.sql, dblord/initdb.d/99-finish.sql, dbmaster/initdb.d/99-finish.sql
There are four users in the database:
* generic root,
* local root
* desec
* desec_test
Hence, the old update command failed as it tried to update both root
users to be 'localhost'.
=> fix(db): init command violated unique constraint

api/desecapi/models.py, docs/domains.rst
This PR
- eliminates the race condition that occurs when users send multiple dynDNS IP update requests, by locking RRsets for update (previously, RRsets with same type/subname would have been attempted to be inserted twice, violating uniqueness)
- minimizes pdns interaction when records have not changed
It also contains a minor docs clarification (based on user feedback).
=> 20171129 fix race condition

api/desecapi/pdns.py
RFC5155, Sec. 10.3 describes NSEC3 iteration count limits based on RSA
and DSA usage scenarios.  As we are using ECDSA 512-bit keys that are
roughly equivalent to a ~3100 RSA key, we picked an NSEC3 iteration
count that would be in the allowable range for such an RSA key.
However, practical experience [1] shows that many resolvers insist on
the maximum iteration count as applicable to a 512 RSA key.  As RFC5155
does not discuss ECDSA keys, they cannot really be blamed.  It is thus
recommendable to lower the count to <= 150.  127 seems like a good
value [2].
[1]: https://www.mail-archive.com/dnsop@ietf.org/msg16148.html
[2]: https://lists.dns-oarc.net/pipermail/dns-operations/2018-January/017174.html
Credits: Viktor Dukhovni
=> fix(api): reduce NSEC3 iterations to 127

api/desecapi/models.py, api/desecapi/views.py, docs/authentication.rst, test/e2e/schemas.js
With this changes, tokens generated in the future will be URL-safe. We send emails using tokens in URLs, so this change is urgent.
=> fix(token): URL-safe token encoding

api/desecapi/migrations/0022_domain_published.py
This did not show up in tests because during testing because the issue
was with migration the existing data rows.  However, migrations are
applied to an empty database, so the buggy code was in fact not tested.
=> fix(api): migration referenced invalid field

api/api/settings.py, api/desecapi/exception_handlers.py
Previously, we returned an unspecific 500 error code. Fixes #134.
Technical details: https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling
=> feat(api): return status 503 when database is unavailable

api/api/settings.py, api/desecapi/exception_handlers.py
Since 7c1b70c4dcb79acdc3b3d86ae772630d4f56f837 we convert OperationalError
exceptions into 503 responses. This does not inhibit the error email being
sent to the admins, but the exception details are replaced by the generic
statement "Service Unavailable: {path}".
At this point, the exception has been turned into a 503 response that raises
a generic 5xx exception leading to the email. The details of the original
exception are gone at that point. However, as admins we'd like to receive
these details.
A nice solution would be to raise a 503 exception that carries the details
without leaking them in the response. However, there is no Django exception
available for the 503 use case.
This commit thus simply adds a supplementary email that reporting the
original error. The effort to avoid the …
=> fix(api): recover OperationalError information when sending 503 reponse

.gitignore, api/requirements.txt
`djangorestframework-bulk` still stops us from upgrading `djangorestframework`. We are currently using 3.7 (12/2017), newest version is 3.9 (03/2019). We should consider replacing it with some other solution or forking it to maintain it ourselves.
=> Upgrade PowerDNS, Django, Djoser, and Some Others

README.md, api/api/settings.py, api/api/urls.py, api/desecapi/authentication.py, api/desecapi/management/commands/sync-from-pdns.py, api/desecapi/tests/testdomains.py, api/desecapi/tests/testdonations.py, api/desecapi/tests/testdyndns12update.py, api/desecapi/tests/testdynupdateauthentication.py, api/desecapi/tests/testprivacychores.py, api/desecapi/tests/testregistration.py, api/desecapi/tests/testrrsets.py, api/desecapi/urls/version_1.py, api/desecapi/urls/version_2.py, api/desecapi/views.py, api/entrypoint-tests.sh, api/requirements.txt, docs/index.rst, docs/lifecycle.rst, test/e2e/schemas.js, test/e2e/spec/api_spec.js
This PR introduces API Version 2, that is a currently an alias for Version 1 and shall later be a stable copy of Version 1. Along the way, this PR cleans up the API definitions and re-organizes them. It also includes end-user documentation for API versioning.
Closes #137
=> Introduce API Versions and Documentation

api/desecapi/views.py
As the request was not processed by rest_framework, there was no
versioning_scheme information present; reversing hence failed and
caused a 500 error after the unlock was successfully commited to
the database.
=> fix(api): reversing failed due to missing info on the request

api/desecapi/tests/testrrsets.py
I found a typo in the RRsets filter used in tests. I appears to have been without consequence; I wonder how that can be? You can probably figure it out quicker as it's your code.
=> fix(tests): typo in RRsets filter

nslord/Dockerfile, nsmaster/Dockerfile
Debian stretch has an old glibc version which triggers a memory leak.
https://github.com/PowerDNS/pdns/issues/5782#issuecomment-335421980
=> fix(ns): switch images from Debian stretch to Ubuntu bionic

api/api/settings_quick_test.py, api/desecapi/authentication.py, api/desecapi/emails.py, api/desecapi/exceptions.py, api/desecapi/management/commands/privacy-chores.py, api/desecapi/management/commands/sync-from-pdns.py, api/desecapi/models.py, api/desecapi/pdns.py, api/desecapi/serializers.py, api/desecapi/templatetags/sepa_extras.py, api/desecapi/tests/base.py, api/desecapi/tests/testdomains.py, api/desecapi/tests/testdonations.py, api/desecapi/tests/testprivacychores.py, api/desecapi/tests/testregistration.py, api/desecapi/tests/testrrsets.py, api/desecapi/urls/version_1.py, api/desecapi/views.py
This commit updates the code style of the API such that the pycharm code inspection is happy on scope
file[desec]:api//*.py&&!file[desec]:api/venv//*&&!file:api/manage.py&&!file:api/api/wsgi.py&&!file[desec]:api/desecapi/migrations//*
with the exception of 50ish stupid "typos" that are mostly test data, names defined in our dependencies or hashes, cryptographic keys, etc.
In more detail, this PR does the following.
- While fixing all pycharm warnings, I found to test bugs, fixed in e1bb69e and 154545e.
- Most of the easy work is done in a82f3ad. 
- 23dffd3 removes a future import that has no effect in python3
- In 64ac60f, an `import *` is converted in explicit imports
- In 571980c, an override of `perform_create` was made compatible with the parent's signature
- Lastly, 23feb3f makes the …
=> Code Style Improvements

www/conf/sites-available/99-desec.conf.var, www/entrypoint.sh
Before deploying this, the host needs to be configured to obtain a certificate for `get.desec.$DESECSTACK_DOMAIN`.
=> feat(www): add get.desec.$DESECSTACK_DOMAIN

www/conf/sites-available/99-desec.conf.var
Sorry, forgot that. It's necessary to that Let's Encrypt can do their ACME challenge without a certificate being there yet.
=> fix(www): also answer get.desec.$DESECSTACK_DOMAIN on port 80

api/desecapi/tests/base.py, api/desecapi/tests/test_authentication.py, api/desecapi/urls/version_1.py
We imported the following URL configuration from Djoser
(djoser/urls/authtoken.py):
urlpatterns = [
url(
r'^token/create/?$',
views.TokenCreateView.as_view(),
name='token-create'
),
url(
r'^token/destroy/?$',
views.TokenDestroyView.as_view(),
name='token-destroy'
),
url(
r'^token/login/?$',
views.TokenCreateView.as_view(),
name='login'
),
url(
r'^token/logout/?$',
views.TokenDestroyView.as_view(),
name='logout'
),
]
Note that the trailing slash is optional in all four routes. While
the api defined four routes overriding the ones defined by Djoser,
they do not cover the case where no trailing slash is given. However,
Djoser's views are not compatible with api's multi-token solution.
This lead to the situation where an attempted login caused a server
error when an user had more than one …
=> Remove Djoser Token Management

api/uwsgi.ini
**TL;DR: the change tracker is not thread-safe, so don't run it multi-threaded.**
The change tracker relies on Django signals to track model changes that need to be propagated to pdns. Django signals are shared across multi-threading, however not across multi-processing.
The state before this PR is to spawn 64 python processes with four threads each. The state after will be to spawn 64 python processes. This has the additional benefit that we can't exhaust the dbapi connection limit anymore, which is currently at it's [default of 151 connections](https://img-9gag-fun.9cache.com/photo/aVYz0yw_700bwp.webp).
As each worker only receives one request at a time, this fixes the bug caused by multi-threading. When using exclusively multi-processing, signals are separated by request.
(Rationale to …
=> Do Not Run API Multi-Threaded

api/desecapi/pdns_change_tracker.py, test/e2e/spec/api_spec.js
This fixes #220, where the API was unable to add an RRset that was
in conflict with an existing CNAME RRset, which was required to be
deleted with the same request.
The fix is somewhat magically, as it depends on
- the order in which updates are send to pdns,
- the changetype that is used to delete RRset in pdns (i.e., "DELETE"
or "REPLACE" with records=[].
For further discussion, see #220.
=> Fixes Conflict when Adding RRsets in Conflict with CNAMES Marked for Deletion

api/api/celery.py, api/api/settings.py, api/api/settings_quick_test.py, api/desecapi/mail_backends.py, api/desecapi/models.py, api/desecapi/tests/test_mail_backends.py
Todos:
- add some more logging at sending time to see which track is being sent from (Celery)
- think about making it nicer, somehow (`mail_backends.py` has two dicts, a class, a function, and a loop ...)
- add some tests. @nils-wisiol , what exactly do you think we should test?
=> feat(api): add fast / slow lane depending on email type, closes #242

api/desecapi/crypto.py, api/desecapi/models.py, api/desecapi/serializers.py, api/desecapi/tests/test_crypto.py, api/desecapi/tests/test_user_management.py, api/desecapi/views.py, api/requirements.txt
Pretty straightforward. Three questions:
- Should we put `SECRET_KEY_SIGN` and `SECRET_KEY_ENCRYPT` in a central place? They are currently in the files where they're needed.
- Should the key derivation be done differently? There's [serious stuff](https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/) out there, but it looks complicated. Let's figure out what's an acceptable approach.
- What's the right way to test this (e.g. that different keys are really being used)?
=> 20191108 encrypt confirmation codes

api/api/settings.py, nsmaster/conf/pdns.conf.var
The catalog zone request currently has 2.9 MB. The previous limit
for request bodies in nsmaster was 2 MB. This comit sets it to
16 MB which should suffice for the forseeable future.
Future work on the replication mechanism can entirely elimitate
the need to provision the zone atomically, so that smaller chunks
can be committed.
=> fix(api,nsmaster): fix max body size to accommodate catalog zone

api/desecapi/management/commands/check-slaves.py
=> fix(api): method name typo

openvpn-server/conf/server.conf
I verified that OpenVPN starts up correctly with this fix.
=> fix(openvpn-server): invalid TCP configuration

www/conf/sites-available/90-desec.api.location.var
Tests have shown that size after compression is around 23%.
Python "requests" automatically asks for gzip, so no need for
change on the slave.
This branch is sandbox-tested.
=> feat(www): compress /api/v1/serials/ endpoint

README.md
Also, this adds an empty `openvpn-server/secrets` directory to the repository, possibly changing the default ownership of that directory from root to `$(whoami)`. Since `.env` is also owned by the user, this should not have big security impact.
=> Update README to include VPN

api/api/settings.py, api/uwsgi.ini, docker-compose.yml, www/conf/nginx.conf
I verified in my local deployment that the metrics numbers now indeed are the sum across workers.
=> 20200331 api multiprocess prometheus

webapp/src/App.vue, webapp/src/router/index.js, webapp/src/validation.js, webapp/src/views/Home.vue, webapp/src/views/ResetPassword.vue, webapp/src/views/SignUp.vue, webapp/src/views/Terms.vue
From your [earlier feedback](https://github.com/desec-io/desec-stack/pull/314#issuecomment-605428852):
> bug: redirect URL to the welcome page contains the wrong domain name for "managed DNS"
Fixed
> optics: let's checkout if tabs could look better than radio buttons
I do not think this is a good solution for two reasons:
a) We can't have tabs on the main page where you can already preselect the account type, before opening the modal. I think though that the UI element to specify the account type should be consistent whenever it appears, i.e. if we have a radio button on the main page, it should also be a radio button in the modal.
b) Different tabs usually are for things that are not mutually exclusive, but instead are not of interest at all times (such as a typical options dialog). Tabs …
=> 20200328 improve signup

nsmaster/Dockerfile, nsmaster/entrypoint.sh
UDP packets originating from nsmaster usually have IP TTL=64 set, but sporadically (~10% of cases) the TTL is 1, and the packet does not live beyond the first hop, which happens to be the VPN server.
I identified two successive queries coming from the same slave, asking for SOA records for two different domains; the packet structure is the same. The nameserver Docker container decided to answer one with TTL=64 in the packet, and the other with TTL=1:
```
23:38:57.064189 IP (tos 0x0, ttl 62, id 16983, offset 0, flags [DF], proto UDP (17), length 78)
10.8.0.21.11569 > 172.16.7.3.53: 1277 [1au] SOA? <masked-1>.dedyn.io. (50)
23:38:57.064358 IP (tos 0x0, ttl 62, id 16984, offset 0, flags [DF], proto UDP (17), length 73)
10.8.0.21.11569 > 172.16.7.3.53: 7951 [1au] SOA? <masked-2>.dedyn.io. …
```
=> fix(nsmaster): set IP TTL for outgoing packets to fix occasional TTL=1

nsmaster/conf/pdns.conf.var
Logs have:
> Limit of simultaneous TCP connections reached - raise max-tcp-connections
Probably due to simultaneous AXFRs.
=> fix(nsmaster): increase max number of DNS TCP connections

api/desecapi/models.py, api/desecapi/pdns_change_tracker.py
This changes the source of randomness for
1. NSEC3 param salt (for new domains), from `random` to `secrets`,
2. authentication tokens, from `urandom` to `secrets`.
Rationale:
1. Creating domains is expensive anyhow, we can afford a little more time spend on the salt generation. 
2. We abstract from the OS and use Python's interface for generating secrets instead of having to worry about the OS interface (like `/dev/random` vs `/dev/urandom`).
=> Update Randomness Sources

webapp/src/App.vue, webapp/src/router/index.js
This just adds a link to a pre-sorted list of projects in our GitHub repository. Downsides:
- we can't add a banner text on top or bottom to explain things
- it leaves our website, doesn't appear in our style
On the other hand, I played around with the GitHub API to retrieve the same info and display it on our website instead. Problems:
- it requires authentication (not sure why, actually)
- this part of the github API is experimental
I created a oneliner to extract the info from GitHub and then copy-paste it into the projects, but this outdates quickly, and progress info may be hard to add (it's not pre-computed by the API and would be needed to be scraped manually). It's along the lines of:
GITHUB_USER=...
GITHUB_TOKEN=...
http -a $GITHUB_USER:$GITHUB_TOKEN …
=> feat(webapp): adds link to GitHub projects page ("roadmap")

dblord/initdb.d/10-pdns-lord.sql, dbmaster/initdb.d/10-pdns-master.sql, nslord/Dockerfile, nsmaster/Dockerfile
This comes with a mandatory database migration on dblord and dbmaster,
https://github.com/PowerDNS/pdns/blob/rel/auth-4.3.x/modules/gmysqlbackend/4.2.0_to_4.3.0_schema.mysql.sql
The commit also contains two small fixes in the database schema that
are not mandatory to apply.
=> BREAKING feat(nslord,nsmaster): upgrade to pdns 4.3

webapp/src/App.vue, webapp/src/store/index.js, webapp/src/views/Home.vue
Adds information about the service disruption today to the home page, and uses the opportunity to introduce an webapp-wide user alerting system that could also be used for error conditions and other important messages.
TODO:
=> Homepage breaking news about service disruption

api/desecapi/pdns_change_tracker.py, api/desecapi/tests/base.py
Currently, nsmaster only receives zone updates on record changes,
but not on RRSIG rollovers. This change makes nsmaster ask for
updates once a day.
After this is merged, we need to run the following query on dblord:
```sql
UPDATE records SET content=REPLACE(content, " 1209600 1209600 2419200 3600", " 86400 86400 2419200 3600") WHERE type = "SOA";
```
=> fix(api): reduce SOA refresh/retry to 1d for automatic RRSIG rollover

api/desecapi/exceptions.py, api/desecapi/pdns_change_tracker.py, api/desecapi/serializers.py, api/desecapi/tests/test_rrsets_bulk.py
This fixes an uncaught exception when processing `[]` via PUT or PATCH on the `rrsets/` endpoint of a domain that already has at least one RRset configured.
The bug was the following: The serializer fetches the to-be-modified RRset instances from the database by adding (`|`-ing) a Django `Q()` object for each of the RRsets given in the payload, starting out from an empty `Q()` object. If the given list of RRsets is empty, the query is just `Q()`, which filters nothing, and all RRsets are retrieved. Instead, no RRsets should be retrieved. This is now ensured by making sure we start out with a queryset that's always empty, and then `|=` the other RRsets.
=> fix(api): fix serializer logic for [] PATCH/PUT payload to rrsets/

webapp/src/views/Terms.vue
This modifies the Terms of Use to
1. remove mention of any retention period for deleted domains (as it is currently not implemented)
1. adds the requirement that domains must be delegated securely (but leaves the operators to choose if domains that are not delegated / not securely delegated will be deleted)
=> Update Terms of Use

webapp/src/views/Home.vue
The commit also reorders POPs so that ns1 takes precendence over ns2 (if there are collisions on the map), and that the POP-order is the same as in other place (e.g. monitoring system).
=> chore(webapp): update Anycast map and related info

api/desecapi/authentication.py, api/desecapi/management/commands/chores.py, api/desecapi/metrics.py, api/desecapi/serializers.py, api/desecapi/tests/test_dyndns12update.py, api/desecapi/views.py, docs/dyndns/update-api.rst
As people ask about it very often, this PR enables using the dynDNS update endpoints regardless of the domain's `minimum_ttl`. The only reason not to do that would load on the secondaries. Once that becomes a problem, we can revisit. (I don't really think it will be an issue.) I went for the "just works" approach, as opposed to adding GUI functionality to change the minimum TTL.
So far, there is no documentation. I'm not sure if there should be (it would encourage such use).
I am also planning to tackle #412 in this PR.
=> 20210216 arbitrary dyn updates

api/desecapi/serializers.py, api/desecapi/tests/test_donations.py, api/desecapi/views.py
The response is generated from serializer.data, which is based on only
request data until .save() is called.  After that, is contains a
representation of the instance created during the .save() call.
This commit moves the instance creation from the view to the .save()
call so that the .data logistics works properly (without actually
saving anything).
=> fix(api): properly return mandate reference for donations, fixes #530

gitzones/Dockerfile
This does not allow login using any password.
=> fix(gitzones): unlock git user to allow ssh-login using pubkey

docs/dyndns/lets-encrypt.rst
According to the errors and warnings returned by certbot
A) --manual-public-ip-logging-ok is depricated, and
B) You are now required to register by mail.
This Pull request replaces the relevant arguments in the documentation
=> fix(docs): Running Certbot headless requires different arguments now

docs/dyndns/configure.rst
Add notes to `ddclient` documentation:
- Clarify use of `usev6` (only on Debian) and point reference docs
- Add note to avoid auto-set IPv6 when unwanted
=> Add notes about ddclient use and avoid use of ipv6

api/requirements.txt
due to https://github.com/celery/celery/issues/6829
Celery 5.0.6 release has been retracted from GitHub, but not from PyPI. Today's deployment of #547 thus caused deployment of the broken version. 
The impact is unknown (it appears that sign-up emails are delivered).
Lesson: Wait for post-merge CI to succeed before deploying.
=> fix(api): don't use Celery 5.0.6 (broken)

docs/dyndns/configure.rst, docs/dyndns/update-api.rst
When I read the documentation for the IP update API, I understood it as something that only works with dedyn.io domains.
I think these changes would make it clearer that they work with a normal deSEC account with any domain, while hopefully not making it less clear that it works with deDyn domains.
=> Clarify documentation for IP update API

api/desecapi/dns.py, api/desecapi/tests/test_rrsets.py, docs/dyndns/configure.rst, test/e2e2/spec/test_api_rr.py
This will be needed once there is a protocol for authenticated bootstrapping of DNSSEC delegations, e.g. for people who need to unsecure there delegation before moving to a non-DNSSEC provider.
If we don't support signaling "DS delete" via CDS/CDNSKEY, the zone owner could still delete the DS records via the registrar/registry, but there's no guarantee that the bootstrapping protocol won't add them back in.
Related: https://github.com/PowerDNS/pdns/issues/10608
=> feat(api): support DS delete algorithm (RFC 8078)

nsmaster/conf/pdns.conf.var
Our secondaries will have different TSIG key configurations, and
nsmaster currently cannot pick the right key.  As a result,
secondaries would discard (some) NOTIFYs.
Outgoing AXFRs can still use TSIG, as the AXFR query contains the
required parameters.
Related: https://github.com/PowerDNS/pdns/issues/10867
=> feat(nsmaster): do not sign outgoing NOTIFYs

api/desecapi/models.py, api/desecapi/tests/test_domains.py, api/desecapi/tests/test_rrsets.py
Related: https://github.com/PowerDNS/pdns/pull/10959
This we deployed PowerDNS 4.6.0, non-compliant RRsets are rejected by pdns. Let's reject them earlier to get a better error message.
=> fix(api): enforce (non-)apex requirements from DNSKEY, DS

api/desecapi/management/commands/stop-abuse.py, api/desecapi/tests/test_stop_abuse.py, docker-compose.test-api.yml, docker-compose.test-e2e2.yml
Introduces the `stop-abuse` command, which takes a list of domain names and:
1. removes all contents of the domains under these names except for `NS` records at the apox, and
2. disables all user accounts associated with any of the given domain names
=> Introduce Management Command for Abuse Cases

.github/workflows/main.yml
Source: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
My PR #621 was blocked by ci because build was temporary failing, but changes in folder `docs` have no influence to the actual build. 
Saves ci time/res and faster ci results for PRs.
Currently `readthedocs.org` runs a check for `docs` and gives a feedback for the PR.
=> change(ci): do not trigger ci build if just docs changed

www/webapp/.browserslistrc, www/webapp/package.json, www/webapp/public/index.html, www/webapp/src/main.js
* `roboto-fontface` is archived
* `fontsource/roboto` provides unicode-range -> smaller font file
* `fontsource/roboto` supports graduated font weight
=> change(webapp): change to newer font library

www/webapp/.browserslistrc, www/webapp/public/index.html
Reduces size of CSS.
Current coverage and simple overview of used `browserslist`:
https://browsersl.ist/?q=%3E+0.5%25%2Clast+2+versions%2CFirefox+ESR%2Cnot+dead
=> feat(webapp): update browserslist - just build for active browsers

test/e2e2/spec/test_www.py, www/conf/sites-available/90-desec.static.location
Webpack inserts small files into the code to minimize the number of requests. This is blocked by the past CSP rule in the browser.
=> fix(webapp): fix CSP header blocking inline font data

test/e2e2/spec/test_www.py, www/conf/sites-available/90-desec.static.content
This PR
1. disables redirects from www.dedyn.$DESECSTACK_DOMAIN and dedyn.$DESECSTACK_DOMAIN to desec.$DESECSTACK_DOMAIN, and
2. enables compression for serving static files.
Rationale:
1. These redirects could associate deSEC with malicious content hosted on dedyn domains. Also, the redirects will become a problem should we ever have more than one local public suffix domain -- each one would require separate certificates and nginx config.
2. Speed up webapp loading @Rotzbua #631 I have not enabled compression for API responses out of an unsubstantiated fear that this may break clients.
Merge #408 first.
=> www: Enable compression for static files

api/desecapi/models/mfa.py, api/desecapi/models/users.py, api/desecapi/tests/test_totp.py, api/desecapi/tests/test_user_management.py, docs/auth/account.rst, docs/dns/domains.rst, www/webapp/src/utils.js, www/webapp/src/views/Console/TOTPVerifyDialog.vue, www/webapp/src/views/MFA.vue
Previously, credentials_changed was only updated when the factor was
first verified. As a result, when an activation link was clicked
twice, the state was unchanged, so the action would attempt to create
the factor again, causing a uniqueness error.
Our `exception_handler` (exception_handlers.py) correctly turned this
into a 409 response, but the ugly database message was exposed, and
an admin email was triggered.
With this commit, the auth action state is invalidated immediately
when the TOTP factor is created.
=> fix(api): update credentials_changed when (unused) TOTP is created

api/desecapi/models/tokens.py, api/desecapi/tests/test_dyndns12update.py, api/desecapi/views/dyndns.py, docs/auth/tokens.rst, docs/dyndns/update-api.rst
Missing:
`_find_ip()` currently raises a `ValueError` when contradicting parameters are given (like `&myip=1.2.3.4,,preserve`). Although this could be converted into a DRF exception, it would be nicer to make this part of some serializer validation error. The problem is that the serializer currently used is not aware of the `""` and `"preserve"` special values.
How do proceed? Should we move the whole query parameter handling to a new dynDNS serializer? (In that case, perhaps it's better to abandon this for now. I thought it's a very small change.) @nils-wisiol
=> Multi-IP updates; base58 tokens

docs/dyndns/update-api.rst
It has happened to me, and I notice it might have happened to others already #246 
I have an active IPv6 connection and when trying to update my record in a single call to `update.dedyn.io` (without passing my current ip as param), it assumes my IPv6 and it turns the record into `AAAA`. 
Instead of passing my current ip as param, we can pass the [curl option --ipv4 or --no-ipv6](https://curl.se/docs/manpage.html#-4) to make use of IPv4 only
Im proposing to add some information and an example about it to the docs.
=> feat(docs):  add information and example to enforce cURL to use ipv4

www/webapp/vue.config.js
Disable inline font to improve FCP (first contentful paint).
Disable to avoid violating CSP rules.
Obsoletes #629
=> fix(webapp): disable inline font

www/webapp/src/views/CrudList.vue
Not really important code style fix, but fixed annoying lint warning while working on the other PRs 😉
=> chore(webapp): remove unnecessary parentheses

www/webapp/src/views/About.vue, www/webapp/src/views/PrivacyPolicy.vue, www/webapp/src/views/Terms.vue
* fix warning Using v-html on component may break component's content vue/no-v-text-v-html-on-component
* add pure html tag to insert html
* fix warning Using v-text on component may break component's content vue/no-v-text-v-html-on-component
* set the "normal" way
Mentioned in #662
=> fix(webapp): warning vue/no-v-text-v-html-on-component

www/html/429.html, www/html/503.html, www/html/check.html, www/webapp/public/robots.txt
Avoid indexation and robot rage of `/api/`.
Some robots may find a link `domain.or/api/xyz` and then try to index the complete api causing a pseudo DOS attack. Good robots will check the robots.txt and stop doing this. Evil robots will do this anyway.
* https://web.dev/robots-txt/
=> feat(webapp): add robots.txt for SEO

docker-compose.yml
It would be nice to observe trends for longer than one month. - This is just event metrics, no personal(izable) data.
=> feat(prometheus): increase retention to 1 year

www/webapp/public/favicon.svg, www/webapp/public/index.html
* Independent of screen resolution
* Modern image format
* `favicon.svg` copy of `logo.notext.svg`
* Removed white border from favicon. logo is black, the white frame disturbs with colored background
=> feat(webapp): add svg favicon

www/webapp/src/views/SignUp.vue
This PR fixes middle click on agreement links (to open it in a new tab without switching). It also fixes the validation error showing up when just clicking on a link. Furthermore, it makes the code more consistent (use `router-link` everywhere instead of `$router.resolve`, use `target="_blank"` everywhere instead of `window.open`).
=> fix(www): middle click on agreement links

api/desecapi/dns.py, api/desecapi/tests/test_rrsets.py, test/e2e2/spec/test_api_rr.py
The previous check was based on the wrong pdns code location. Consultation on pdns IRC revealed the right one.
Fixes regression from 0605f3879012ce6dc4c06f5d7711875348c9e468
=> fix(api): allow underscores in CNAME targets

www/webapp/package.json, www/webapp/src/App.vue, www/webapp/src/components/DonateDirectDebitForm.vue, www/webapp/src/components/Field/RecordList.vue, www/webapp/src/plugins/vuetify.js, www/webapp/src/views/Console/DomainSetupDialog.vue, www/webapp/src/views/Console/TOTPVerifyDialog.vue, www/webapp/src/views/CrudList.vue, www/webapp/src/views/CrudListDomain.vue, www/webapp/src/views/DonatePage.vue, www/webapp/src/views/HomePage.vue, www/webapp/src/views/MFA.vue
Use tree shakeable version instead of big webfont.
Login, signup seems to need some refactoring. Migration later.
Partial migration of #710
=> Migrate from `@mdi/font` to `@mdi/js`

dbapi/Dockerfile, dbmaster/Dockerfile, nslord/Dockerfile, nsmaster/Dockerfile
This PR unifies the procedures of some similar Dockerfiles that we have such that they have more common steps, which I hope can reduce the build time and total image size.
This results in some images having unnecessary installations, in particular:
- nslord: iptables iproute2 pdns-backend-pgsql postgresql-client-10
- nsmaster: faketime pdns-backend-mysql
The last 15 builds on GitHub took 478s on average (std: 53s). Let's see how long it takes in this PR. (Data: 6:37 9:07 8:23 7:03 7:26 7:19 7:24 7:08 7:22 7:18 9:11 8:56 8:32 9:32 7:53)
Alternatives to this PR are:
1. Wait (possibly) longer for builds/deployments
2. More docker image layers
- removing apt package lists requires longer build time for repeated `apt update`
- not removing apt package lists requires larger layer sizes
=> feat(): larger common prefixes of Dockerfiles to speed up building

www/webapp/src/components/Field/RecordItem.vue, www/webapp/src/views/DynSetup.vue
`substr()` is deprecated.
Replace by `substring` or `slice`.
Used `slice` because it is used in the project.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
=> fix(webapp): migrate deprecated `substr()`

www/webapp/package.json, www/webapp/src/components/Field/TimeAgo.vue, www/webapp/src/main.js
As @lukaslihotzki mentioned in #699 the dependency `javascript-time-ago` is not used.
The time ago component `vue-timeago` is a wrapper for `date-fns`. The component is just used once and limited functionality so it could be implement very easy. This simplifies the dependency graph and for the migration to vue3 there is no need for replacement.
=> feat(webapp): replace dependency `vue-timeago`

www/webapp/src/components/GenericActionHandler.vue, www/webapp/src/views/ConfirmationPage.vue, www/webapp/src/views/CrudListDomain.vue, www/webapp/src/views/CrudListRecord.vue, www/webapp/src/views/CrudListTOTP.vue, www/webapp/src/views/CrudListToken.vue
Renaming the components in pr  #691 caused runtime issues because constant strings are used.
Use component name directly.
=> feat(webapp): use component name instead of string

www/webapp/src/components/DonateDirectDebitForm.vue, www/webapp/src/views/ChangeEmail.vue, www/webapp/src/views/DeleteAccount.vue, www/webapp/src/views/LoginPage.vue, www/webapp/src/views/ResetPassword.vue, www/webapp/src/views/SignUp.vue
Disable form instead of every input field.
Vuetify did not support the disable-forms-feature from the beginning. Today it supports to disable the form instead of every single form input.
Signup: domain selection is not disabled.
https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.0
=> fix(webapp): disable complete form not every input field

www/webapp/.eslintrc.js, www/webapp/src/App.vue, www/webapp/src/components/Field/RecordList.vue, www/webapp/src/views/AboutPage.vue, www/webapp/src/views/Console/TOTPVerifyDialog.vue, www/webapp/src/views/CrudList.vue, www/webapp/src/views/DonatePage.vue, www/webapp/src/views/DynSetup.vue, www/webapp/src/views/HomePage.vue, www/webapp/src/views/ImpressumPage.vue, www/webapp/src/views/PrivacyPolicy.vue, www/webapp/src/views/TermsPage.vue
Two styles are used in project:
* `{{abc}}`
* `{{ abc }}`
With spaces `{{ abc }}` is eslint default and forced by this new rule.
Style can be automatically applied by `npm lint --fix`.
https://eslint.vuejs.org/rules/mustache-interpolation-spacing.html
=> feat(webapp): add eslint rule for mustache style

www/webapp/.eslintrc.js, www/webapp/package.json, www/webapp/src/App.vue, www/webapp/src/components/Field/RecordList.vue, www/webapp/src/main.js, www/webapp/src/views/AboutPage.vue, www/webapp/src/views/Console/TOTPVerifyDialog.vue, www/webapp/src/views/CrudList.vue, www/webapp/src/views/DomainSetup.vue, www/webapp/src/views/DonatePage.vue, www/webapp/src/views/DynSetup.vue, www/webapp/src/views/HomePage.vue, www/webapp/src/views/ImpressumPage.vue, www/webapp/src/views/PrivacyPolicy.vue, www/webapp/src/views/TermsPage.vue
From #699 as preparation for vue3. Native implementation is simpler than an additional dependency.
=> refactor(webapp): replace `vue-clipboard2`

api/Dockerfile, www/webapp/.eslintrc.js, www/webapp/src/components/Field/RecordItem.vue, www/webapp/src/views/ConfirmationPage.vue
Some APIs are deprecated with vue3. A few of them can be migrated despite of vue2.
Added `eslint` rules to prevent future changes adding them back in.
=> feat(webapp): preparation for vue3

www/webapp/.eslintrc.js, www/webapp/package.json
Remove dependency on vue-cli to enable migration to vite.
=> feat(webapp): use `eslint` as standalone

www/webapp/.eslintrc.js, www/webapp/package.json
Not all files are processed by `eslint`.
Parser was not set correctly.
#770
=> fix(webapp): `eslint` regression by #770

docs/dyndns/configure.rst
Daemon is needed in the most cases, as by default the user isn't expected to enable it by themselves or via a separate cron. This can may prevent from unexpected outages of the host.
=> docs: Add daemon timeout to ddclient config

test/e2e2/spec/test_www.py, www/conf/sites-available/90-desec.static.location
Add inline script hashes for `@vitejs/plugin-legacy`:
Add the corresponding hashes to your script-src list:
sha256-MS6/3FCg4WjP9gwgaBGwLpRCY6fZBgwmhVCdrPrNf3E=
sha256-tQjf8gvb2ROOMapIxFvFAYBeUJ0v1HCbOcSmDNXGtDo=
sha256-4y/gEB2/KIwZFTfNqwXJq4olzvmQ0S214m9jwKgNXoc=
sha256-+5XkZFazzJo8n0iOP4ti/cLCMUudTf//Mzkb7xNPXIc=
Source:
https://github.com/vitejs/vite/tree/main/packages/plugin-legacy#content-security-policy
fixes #788
=> fix(webapp): add missing hashes to CSP

openvpn-server/conf/server.conf
Fixes warning:
* Note: Treating option '--ncp-ciphers' as  '--data-ciphers' (renamed in OpenVPN 2.5).
* --cipher is not set. Previous OpenVPN version defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
* #795
* Source: https://community.openvpn.net/openvpn/wiki/CipherNegotiation
=> fix(openvpn): update config for v2.5

api/desecapi/management/commands/chores.py, www/webapp/src/views/ImpressumPage.vue
RRsetSerializer now assumes there's a request with a token, and checks its permission. The watchdog updates aren't based on a request, so we now use the model directly (instead of the serializer).
Tested on my machine. (The model interface also has unit tests.)
=> fix(api): don't use serializer for watchdog zone updates

www/webapp/package.json, www/webapp/src/components/ActivateAccountActionHandler.vue, www/webapp/src/components/ResetPasswordActionHandler.vue, www/webapp/src/main.js, www/webapp/src/views/ChangeEmail.vue, www/webapp/src/views/DeleteAccount.vue, www/webapp/src/views/HomePage.vue, www/webapp/src/views/LoginPage.vue, www/webapp/src/views/ResetPassword.vue, www/webapp/src/views/SignUp.vue
Final migration. Mdi webfont not used anymore.
Use tree shakeable version instead of big webfont.
Closes #710
=> feat(webapp): migrate from @mdi/font to @mdi/js

.github/dependabot.yml
eslint v9 has breaking changes and plugins are not yet fully compatible.
So let dependabot ignore `eslint`.
=> fix(webapp): dependabot ignore `eslint`

api/desecapi/tests/base.py, test/e2e2/conftest.py, test/e2e2/spec/test_api_rr.py
New since python 3.9:
https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
=> feat(tests): use built-in typing

docs/conf.py, docs/make.bat, docs/requirements.txt
- simplify config
- Remove deprecated `html_theme_path`
- Update `make.bat` to current sphinx-quickstart template
- Autoupdate copyright year
=> chore(docs): simplify config

www/Dockerfile, www/conf/conf.d/ssl.conf
Enables key agreement for TLS connections of www using hybrid PQC schemes (ECDHE + ML-KEM). Does not remove support for pure classical schemes (ECDHE only). Does not remove support for non-elliptic-curve DHE-RSA key agreement.
Hybrid PQC schemes using ML-KEM are supported from Chrome 131 onward; Firefox from 132 onward.
=> feat(www): optional hybrid PQC key exchange for TLS connections

api/desecapi/models/records.py, www/webapp/src/components/Field/GenericText.vue, www/webapp/src/views/CrudListRecord.vue
Previously, the hint was shown persistently in standard color (grey). It's now hidden by default, and appears in orange when subname ends with domain name. The message does not block form submission (it is not a validation error).
=> Webapp: warn if subname ends with domain name

docs/auth/account.rst, docs/auth/tokens.rst, docs/dns/domains.rst, docs/dns/rrsets.rst, docs/index.rst, docs/quickstart.rst
Based on the Post [Unnecessary use of curl -X](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/) is the parameter `-X` unnecessary for `POST` and `GET` calls.
This PR removed the unnecessary `-X` for that examples.
=> Replace -X in curl commands
