desec-io/desec-stack

api/desecapi/templates/emails/from.txt, nslord/cronhook/secure-zones.sh
=> 20170418 fix rapid notify

api/desecapi/views.py
just simplified a piece of code :+1:
=> fix(domain): simplify domain name verfication

api/desecapi/pdns.py
=> fix(pdns): check key type before processing response

api/desecapi/serializers.py
=> fix(api): remove timestamps from domain serialization

nslord/cronhook/secure-zones.sh
- Deal correctly with domain names starting with dashes or otherwise
weird
- Also, don't use unnecessarily large amounts of entropy for salting
=> fix(nslord): harden secure-zones script, fixes #18

api/desecapi/models.py, api/desecapi/pdns.py, api/desecapi/tests/testdomains.py, api/desecapi/tests/testdyndns12update.py
=> fix(api): data structure typo. explicit is better than implicit!

api/Dockerfile, api/desecapi/migrations/0001_initial.py, api/desecapi/models.py, api/desecapi/settings.py, api/desecapi/tests/testdomains.py, api/desecapi/tests/testdonations.py, api/desecapi/tests/testdyndns12update.py, api/desecapi/tests/testdynupdateauthentication.py, api/desecapi/tests/testregistration.py, api/desecapi/tests/testrrsets.py, api/desecapi/urls.py, api/desecapi/views.py, api/requirements.txt, docs/authentication.rst, docs/endpoint-reference.rst, test/e2e/spec/api_spec.js, test/e2e/spec/dyndns_spec.js
- django fixes a bug where users without password cannot reset their
password
- on_delete mandatory on all ForeignKeys (including old migrations!)
- djoser changed urls
- django's url reverse method moved
- added new djoser routes to urls and refactored import
- user is_authenticated became a property
- python 3.7
We can't upgrade djangorestframework right now because
djangorestframework-bulk is blocking it.
We can't fully upgrade djoser due to
https://github.com/sunscrapers/djoser/issues/312
https://github.com/sunscrapers/djoser/issues/308
=> upgrade dependencies

docs/authentication.rst
just to make copy & paste easier
=> fix(docs): trivial doc fix

api/api/settings.py, api/desecapi/authentication.py, api/desecapi/models.py, api/desecapi/tests/testdyndns12update.py, api/desecapi/views.py
Mainly cleaning up installed apps and middleware stuff
=> 20190217 settings

api/entrypoint.sh, docker-compose.dev.yml, docker-compose.test-api.yml, docker-compose.test-e2e.yml, docker-compose.yml, nslord/entrypoint.sh, nsmaster/entrypoint.sh
Rationale: https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html
=> feat(): use init system inside Docker containers, fixes #113

api/desecapi/tests/test_rrsets.py, api/desecapi/views.py
get_object() is now very close to the standard DRF implementation
=> fix(api): fix unknown RRset PUT/PATCH on RRsetDetail endpoint, fix #229

api/desecapi/urls/version_1.py, api/desecapi/views.py, api/requirements.txt
=> feat(api): remove dyn endpoint, closes #193

api/desecapi/tests/test_user_management.py, api/desecapi/views.py
=> fix(api): return 409 on delete requests if user still has domains

api/api/settings.py, api/api/settings_quick_test.py, api/desecapi/pagination.py, api/desecapi/serializers.py, api/desecapi/tests/base.py, api/desecapi/tests/test_domains.py, api/desecapi/tests/test_rrsets.py, docs/domains.rst, docs/rrsets.rst, test/e2e/run_tests, test/e2e/schemas.js
Functionality is there. What's missing:
- tests
- docs
=> 20190719 rrsets pagination

api/desecapi/exceptions.py, api/desecapi/tests/base.py, api/desecapi/tests/test_dyndns12update.py
This fixes the error emails we've getting every 10 minutes
=> fix(api): fixed exception format

api/desecapi/serializers.py, api/desecapi/tests/base.py, api/desecapi/tests/test_rrsets.py, api/desecapi/tests/test_rrsets_bulk.py, api/desecapi/views.py
This fixes the bug reported to our support mailbox today at 09:02.
=> fix(api): correctly handle POST/PUT/PATCH with empty payload

webapp/src/App.vue
So this recently on some other page and figured I'd give it a try. I think it's cute :-)
=> feat(webapp): hearty times

www/conf/sites-available/15-dedyn-update.conf.var
=> 20200414 fix update6 tls

api/entrypoint.sh, docker-compose.yml
https://github.com/opencontainers/runc/issues/1647 looks related.
=> fix(api): force setting metrics directory permissions, fixes #333

api/desecapi/crypto.py, api/desecapi/exception_handlers.py, api/desecapi/mail_backends.py, api/desecapi/metrics.py, api/desecapi/models.py, api/desecapi/pdns.py, api/desecapi/pdns_change_tracker.py, api/desecapi/serializers.py, api/desecapi/throttling.py, api/desecapi/views.py
Added metrics to prometheus, ready for review.
P.S. need review also on if something is missing
=> 20200422 prometheus akash

README.md, api/Dockerfile
=> README fixes and chores

.github/workflows/main.yml, api/Dockerfile, api/api/settings.py, api/requirements.txt
=> feat(): add log output to GitHub CI action

webapp/src/App.vue
Could be more prominent, but not sure how.
=> feat(webapp): adds link to desec-status.net

api/desecapi/management/commands/chores.py
Use from the alerting system to check that chores are running.
=> 20200611 healthcheck timestamp chore

api/cronhook/crontab, webapp/src/components/Field/RRSet.vue, webapp/src/components/Field/Record.vue, webapp/src/components/Field/RecordTXT.vue, webapp/src/components/Field/TTL.vue, webapp/src/views/CrudList.vue, webapp/src/views/Domain/CrudDomain.vue
- schedule savenger daily
- improve GUI validation
I figured both is not urgent and changes are small, so I created just one PR to avoid rebasing and other logistics.
=> 20200810 miscellaneous fixes

docs/dyndns/configure.rst, docs/dyndns/update-api.rst
=> Dyndns doc update

webapp/src/components/Field/RecordCNAME.vue
Received a corresponding report via email. Tested locally.
=> fix(webapp): allow _ in CNAME targets

test/e2e/spec/api_spec.js, webapp/src/App.vue, webapp/src/views/Home.vue
- remove old news
- add today's news
- minor modifications in the alert visualization
on my computer it looks like this
=> Breaking News & e2e Fix

api/desecapi/pdns_change_tracker.py, api/desecapi/tests/base.py, api/desecapi/tests/test_rrsets.py, api/desecapi/tests/test_rrsets_bulk.py, test/e2e/spec/api_spec.js, webapp/src/components/Field/GenericText.vue, webapp/src/components/Field/RRSetType.vue, webapp/src/components/Field/Record.vue, webapp/src/components/Field/RecordList.vue, webapp/src/components/Field/TTL.vue, webapp/src/views/CrudList.vue
This fixes an issue with SOA record validation of nic.it, which does not allow the SOA to contain domain names that do not resolve.
https://dns-check.nic.it/
=> fix(api): only use resolvable domain names in SOA record

webapp/src/components/Field/GenericText.vue, webapp/src/components/Field/RRSetType.vue, webapp/src/components/Field/Record.vue, webapp/src/components/Field/RecordList.vue, webapp/src/components/Field/TTL.vue, webapp/src/views/CrudList.vue
Fixes two webapp UI bugs:
- maintain CrudTable row highlighting (error / changed) when changing sort order
- correct display of Record field contents when data changes
Also, this refactors the code in places to increase readability and to follow vue.js patterns.
=> Webapp Bug Fixes and Code Style

api/Dockerfile, api/desecapi/authentication.py, api/desecapi/models.py, api/desecapi/pdns.py, api/desecapi/tests/base.py, api/desecapi/tests/test_domains.py, api/desecapi/tests/test_dyndns12update.py, api/desecapi/views.py, docs/dyndns/update-api.rst
That was easier than I thought. Need to add tests and docs, but that should be straightforward, too.
You might want to take a look at `utils.get_domain_for_qname()`.
=> 20210217 dyn subdomains

dblord/initdb.d/00-init.sql, dbmaster/initdb.d/00-init.sql, docs/dns/domains.rst, docs/dyndns/lets-encrypt.rst, test/e2e2/conftest.py, webapp/src/views/Terms.vue, www/conf/sites-available/envreplace.sh
#
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ).
=> spelling fixes

api/desecapi/serializers.py, webapp/src/views/Donate.vue
- A no-op code cleanup
- Small change to donation texts
=> 20210518 kleinkram

webapp/src/components/DonateDirectDebitForm.vue, webapp/src/views/Console/DomainSetupDialog.vue, webapp/src/views/DomainSetup.vue
=> 20210614 domain dialog

api/api/settings.py, api/desecapi/models.py, api/desecapi/tests/test_domains.py, api/desecapi/tests/test_dyndns12update.py, api/desecapi/views.py, docs/rate-limits.rst
=> Fix wildcard domains in filter_qname

docs/dyndns/configure.rst, docs/dyndns/update-api.rst, docs/rate-limits.rst
added tip about multiple subdomains
=> added tip about multiple subdomains

www/webapp/.gitignore
=> fix(webapp): add build output folder `dist` to gitignore

www/webapp/src/App.vue, www/webapp/src/components/DonateDirectDebitForm.vue, www/webapp/src/main.js, www/webapp/src/router/index.js, www/webapp/src/views/ChangeEmail.vue, www/webapp/src/views/Confirmation.vue, www/webapp/src/views/DynSetup.vue, www/webapp/src/views/Home.vue, www/webapp/src/views/Login.vue, www/webapp/src/views/ResetPassword.vue, www/webapp/src/views/SignUp.vue, www/webapp/src/views/TokenList.vue
From folder relative import to project `src/` (`@`) relative import path.
None. More common code style.
=> refactor(webapp): migrate import path

www/webapp/src/components/GenericActionHandler.vue, www/webapp/src/router/index.js, www/webapp/src/utils.js, www/webapp/src/views/SignUp.vue
Use strict equality for type safety.
=> fix(webapp): use strict equality

www/webapp/src/App.vue, www/webapp/src/router/index.js, www/webapp/src/views/Home.vue
Since every service/URL supports HTTPS let's use it.
=> fix(webapp): force https for supported urls

www/webapp/src/views/About.vue, www/webapp/src/views/PrivacyPolicy.vue, www/webapp/src/views/Terms.vue
The next issue or pr will be evil 😈  😄
=> fix(webapp): tiny typo

www/html/429.html, www/html/503.html, www/html/check.html
* search engines should not index error pages
* replace obsolete html with css
* fix invalid html
Checked by:
https://validator.w3.org/#validate_by_input
=> fix(www): fix wrong html tag, doctype, javascript

www/webapp/src/views/About.vue, www/webapp/src/views/Home.vue, www/webapp/src/views/PrivacyPolicy.vue, www/webapp/src/views/Terms.vue
Some names are wrong. Has no impact.
=> fix(webapp): fix naming

www/webapp/.eslintrc.js, www/webapp/vue.config.js
=> feat(webapp): add typehint to config

api/desecapi/dns.py, api/desecapi/models/records.py, api/desecapi/pdns.py, api/desecapi/serializers/tokens.py, api/desecapi/tests/test_rrsets.py, docs/auth/tokens.rst, www/webapp/src/views/Home.vue, www/webapp/src/views/SignUp.vue
This reverts commit 1c6a6878708e43a5eba0bbf699219f33a4ad9c57.
=> Various fixes, including Revert "feat(api): look up nslord address only once"

www/webapp/public/index.html
=> feat(www): improve noscript for better SEO and text browsers

www/webapp/src/views/Donate.vue
As suggested in https://talk.desec.io/t/provide-qr-code-for-bank-transfer/623
=> feat(webapp): show bank transfer info as EPC QR code

www/webapp/src/components/Field/RecordList.vue
Fix bug introduced by #691 .
Closes #739 .
=> fix(webapp): RRset value field doesn't update

www/webapp/package.json, www/webapp/src/App.vue, www/webapp/src/components/DonateDirectDebitForm.vue, www/webapp/src/components/Field/RecordList.vue, www/webapp/src/plugins/vuetify.js, www/webapp/src/views/Console/DomainSetupDialog.vue, www/webapp/src/views/Console/TOTPVerifyDialog.vue, www/webapp/src/views/CrudList.vue, www/webapp/src/views/CrudListDomain.vue, www/webapp/src/views/DonatePage.vue, www/webapp/src/views/HomePage.vue, www/webapp/src/views/MFA.vue
* Change: lazy load image
* Fix image alt text
=> feat(webapp): lazy load image

www/webapp/src/components/ErrorAlert.vue, www/webapp/src/components/Field/RRSetType.vue, www/webapp/src/components/Field/RecordItem.vue, www/webapp/src/components/Field/RecordList.vue, www/webapp/src/components/Field/TimeAgo.vue, www/webapp/src/views/LoginPage.vue
=> fix(webapp): remove unused style tags

www/webapp/src/views/DonatePage.vue
Should be direct import like the other import in 2fa component.
=> fix(webapp): wrong import path for qrcode

www/webapp/src/components/Field/GenericTextarea.vue, www/webapp/src/components/Field/Record/SVCB.vue
=> fix(webapp): wrong component name

www/webapp/src/components/Field/GenericTextarea.vue, www/webapp/src/components/Field/Record/SVCB.vue, www/webapp/src/views/DomainSetup.vue
Prettify the interaction result notice.
=> feat(webapp): add icon to copy to clipboard snackbar

README.md, www/README.md
=> fix(docs): fix typos in README

docs/dns/rrsets.rst
=> Fix typo "responds"

docs/dns/rrsets.rst
Target not available. Update to new headings.
=> fix(docs): update outdated links

.github/dependabot.yml
=> feat(dependabot): group dependency updates

.readthedocs.yaml, docs/requirements.txt, www/webapp/src/components/Field/RecordDNSKEY.vue, www/webapp/src/components/Field/RecordDS.vue, www/webapp/src/components/Field/RecordItem.vue, www/webapp/src/components/Field/RecordList.vue, www/webapp/src/views/Console/DomainSetupDialog.vue, www/webapp/src/views/CrudList.vue, www/webapp/src/views/CrudListDomain.vue, www/webapp/src/views/CrudListRecord.vue, www/webapp/src/views/CrudListToken.vue, www/webapp/src/views/DomainSetup.vue
Ready for review.
(Still need to adjust an error detail when user is not authenticated, but everything else is ready for review.)
=> New DS setup dialog

www/webapp/src/views/AboutPage.vue, www/webapp/src/views/DonatePage.vue, www/webapp/src/views/HomePage.vue, www/webapp/src/views/TermsPage.vue
fix missing migrations to vuetify v2
https://v2.vuetifyjs.com/en/getting-started/upgrade-guide/#typography
fix illegal paragraph in header.
text size is a bit smaller.
=> fix(webapp): class rename subheading → subtitle-1

api/api/settings_quick_test.py, api/desecapi/models/domains.py, api/desecapi/serializers/domains.py, api/desecapi/tests/base.py, api/desecapi/tests/test_rrsets.py, api/desecapi/tests/test_user_management.py, www/webapp/package.json, www/webapp/src/components/Field/TimeAgo.vue
Import is a bit different.
Suppress #873 #876
=> chore(webapp): bump date-fns from 2.30.0 to 3.3.1

www/webapp/src/App.vue, www/webapp/src/views/AboutPage.vue, www/webapp/src/views/DonatePage.vue, www/webapp/src/views/HomePage.vue, www/webapp/vite.config.js
`require` not required anymore 😄 
`require` does not work with Vue3.
=> fix(webapp): transform asset url for `v-img`

docs/dyndns/update-api.rst
Wrong Update URL that will only update IPv6 instead of both.
=> error in update url

api/desecapi/management/commands/check-secondaries.py, api/desecapi/models/donation.py, www/webapp/src/components/DonateDirectDebitForm.vue, www/webapp/src/views/DonatePage.vue
=> fix(api): typo

README.md, www/webapp/src/views/CrudListDomain.vue
Two small miscellaneous changes to ease debugging.
=> Correctly display domain limits and extend README

docker-compose.yml
Related: b27e0404cbb743d42b18782d501458f13960631c
=> fix(dbapi): increase max_connections to accommodate api workers

docs/dns/rrsets.rst
To be able to automate the TLSA change is it helpful to automate the generation and extraction of the TLSA hash. This commit adds 2 examples how this automation can be done.
This is my first restructured text maybe there are some issues with the format.
=> Add command to get TLSA hash
